# Generated by Django 3.0.4 on 2020-03-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200323_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='wallet',
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
